name: "after-release"
on:
  workflow_run:
    workflows: [hello-world]
    types:
      - completed
jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: |
            echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
            shortSHA=`echo ${GITHUB_SHA} | cut -c1-8`
            echo "GIT_SHORT_SHA=${shortSHA}" >> $GITHUB_ENV
            projectNames="${GITHUB_REPOSITORY#*/}"
            expansion="${projectNames#*-}"
            echo "TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
            
    - name: Notify
      uses: rjstone/discord-webhook-notify@v1.1.1
      with:
        severity: info
        description: |
          **Release ${{env.TAG}} Aplicada!**
        details: |
          **Branch:** ${{env.GIT_BRANCH}}
          - [Default Download](${{github.server_url}}/${{ github.repository }}/releases/)
        footer: Desenvolvido por Solinftec! We Are Solinftec!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}