name: "after-release"
on:
  workflow_run:
    workflows: [hello-world]
    types:
      - completed
jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
    - name: Test Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
          severity: info
          details: Release Aplicada!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}