name: "after-release"
on:
  workflow_run:
    workflows: [hello-world]
    types:
      - completed
jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
        - name: Actions for Discord
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          uses: Ilshidur/action-discord@master
          with: 
              args: '@Qualidade Release do {{ EVENT_PAYLOAD.repository.full_name }} Aplicada! Versão gerada: ${GITHUB_REF##*/}.'