name: hello-world
on:
  push:
    branches:
      - "main"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get pull request URLs or commit URLs from commits
        id: get_prs_or_commits
        run: |
          pr_or_commit_urls=""
          for sha in $(jq -r '.commits[].id' < $GITHUB_EVENT_PATH); do
            pr_numbers=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/$sha/pulls" \
              -H "Accept: application/vnd.github.groot-preview+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" | jq -r '.[].number')
            if [ -n "$pr_numbers" ]; then
              for pr in $pr_numbers; do
                pr_url="https://github.com/${{ github.repository }}/pull/$pr"
                pr_or_commit_urls+="$pr_url\n"
              done
            else
              commit_url="https://github.com/${{ github.repository }}/commit/$sha"
              pr_or_commit_urls+="$commit_url\n"
            fi
          done
          if [ -z "$pr_or_commit_urls" ]; then
            pr_or_commit_urls="N/A"
          fi
          echo "PR or Commit URLs:"
          echo -e "$pr_or_commit_urls"
          echo "::set-output name=pr_or_commit_urls::$pr_or_commit_urls"


      - name: Notify Discord
        if: steps.get_prs.outputs.pr_urls != 'N/A'
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: Homologação
          text: | 
            <@&689593112271519745> Homologação **SGPA-API** Aplicada!
            - ${{ steps.get_prs_or_commits.outputs.pr_or_commit_urls }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
