name: hello-world
on:
  release:
    types:
      - "released"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: my-step
        run: echo "Hello World!"
      - name: Get release info
        id: get_release
        run: |
          release_data=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}")
          echo "$release_data"
          echo "::set-output name=release_id::$(echo "$release_data" | jq -r .id)"
          echo "::set-output name=release_name::$(echo "$release_data" | jq -r .name)"
          echo "::set-output name=release_body::$(echo "$release_data" | jq -r .body)"
          echo "::set-output name=release_html_url::$(echo "$release_data" | jq -r .html_url)"

      - name: Display release info
        run: |
          echo "Release ID: ${{ steps.get_release.outputs.release_id }}"
          echo "Release Name: ${{ steps.get_release.outputs.release_name }}"
          echo "Release Body: ${{ steps.get_release.outputs.release_body }}"
          echo "Release URL: ${{ steps.get_release.outputs.release_html_url }}"


      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: Homologacao
          text: <@&689593112271519745> Homologação SGPA-API Atualizada! **Release Name**":" ${{ steps.get_release.outputs.release_name }}\n ${{ steps.get_release.outputs.release_body }}\n **Release URL**":" ${{ steps.get_release.outputs.release_html_url }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


          