name: hello-world
on:
  push:
    branches:
      - "main"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the latest merge commit
        id: get_latest_merge
        run: |
          latest_merge_commit=$(git log --merges -n 1 --format="%H" || echo "N/A")
          echo "Latest merge commit: $latest_merge_commit"
          echo "::set-output name=latest_merge_commit::$latest_merge_commit"

      - name: Get merged pull requests since the latest merge
        id: get_prs
        if: steps.get_latest_merge.outputs.latest_merge_commit != 'N/A'
        run: |
          latest_merge_commit="${{ steps.get_latest_merge.outputs.latest_merge_commit }}"
          pr_urls=""
          prs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/commits/$latest_merge_commit/pulls" | jq -r '.[] | .html_url')
          if [ -z "$prs" ]; then
            pr_urls="N/A"
          else
            pr_urls="$prs"
          fi
          echo "PR URLs:"
          echo -e "$pr_urls"
          echo "::set-output name=pr_urls::$pr_urls"

      - name: Notify Discord
        if: steps.get_prs.outputs.pr_urls != 'N/A'
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: Homologação
          text: | 
            <@&689593112271519745> Homologação **SGPA-API** Aplicada!
             - **PullRequests:** ${{ steps.get_prs.outputs.pr_urls }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
